
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BlocksLogo: typeof import("../app/components/blocks/logo.vue")['default']
export const MenusFooter: typeof import("../app/components/menus/Footer.vue")['default']
export const MenusHeader: typeof import("../app/components/menus/Header.vue")['default']
export const MenusEcosystemmenu: typeof import("../app/components/menus/ecosystemmenu.vue")['default']
export const MenusLowernav: typeof import("../app/components/menus/lowernav.vue")['default']
export const MenusMobilesearch: typeof import("../app/components/menus/mobilesearch.vue")['default']
export const MenusSidebarnav: typeof import("../app/components/menus/sidebarnav.vue")['default']
export const MenusTopmenu: typeof import("../app/components/menus/topmenu.vue")['default']
export const Gallery: typeof import("../node_modules/@mframework/layer-shared/app/components/Gallery/Gallery.vue")['default']
export const Heading: typeof import("../node_modules/@mframework/layer-shared/app/components/Heading/Heading.vue")['default']
export const HeadingTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/Heading/types")['default']
export const MediaAudioGallery: typeof import("../node_modules/@mframework/layer-shared/app/components/media/audioGallery.vue")['default']
export const MediaDragDropUpload: typeof import("../node_modules/@mframework/layer-shared/app/components/media/dragDropUpload.vue")['default']
export const MediaFullscreenMediaModal: typeof import("../node_modules/@mframework/layer-shared/app/components/media/fullscreenMediaModal.vue")['default']
export const MediaImageCard: typeof import("../node_modules/@mframework/layer-shared/app/components/media/imageCard.vue")['default']
export const MediaImageGallery: typeof import("../node_modules/@mframework/layer-shared/app/components/media/imageGallery.vue")['default']
export const MediaCard: typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaCard.vue")['default']
export const MediaCarousel: typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaCarousel.vue")['default']
export const MediaFolderSidebar: typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaFolderSidebar.vue")['default']
export const MediaPlayer: typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaPlayer.vue")['default']
export const MediaSearchBar: typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaSearchBar.vue")['default']
export const MediaVideoGallery: typeof import("../node_modules/@mframework/layer-shared/app/components/media/videoGallery.vue")['default']
export const UiAccordionItem: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/AccordionItem/AccordionItem.vue")['default']
export const UiAccordionItemTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/AccordionItem/types")['default']
export const UiAlert: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Alert/Alert.vue")['default']
export const UiAlertTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Alert/types")['default']
export const UiBreadcrumbs: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Breadcrumbs/Breadcrumbs.vue")['default']
export const UiBreadcrumbsTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Breadcrumbs/types")['default']
export const UiCartProductCard: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CartProductCard/CartProductCard.vue")['default']
export const UiCartProductCardTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CartProductCard/types")['default']
export const UiCategoryCard: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CategoryCard/CategoryCard.vue")['default']
export const UiCategoryCardTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CategoryCard/types")['default']
export const UiDisplay: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Display/Display.vue")['default']
export const UiDisplayTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Display/types")['default']
export const UiDivider: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Divider/Divider.vue")['default']
export const UiFooter: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Footer.vue")['default']
export const UiFormHelperText: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormHelperText.vue")['default']
export const UiFormLabel: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormLabel.vue")['default']
export const UiFormPasswordInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormPasswordInput.vue")['default']
export const UiHero: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Hero/Hero.vue")['default']
export const UiHeroTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Hero/types")['default']
export const UiMButton: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/MButton.vue")['default']
export const UiModal: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Modal/Modal.vue")['default']
export const UiModalTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Modal/types")['default']
export const UiMotionable: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Motionable.vue")['default']
export const UiNavbarBottom: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/NavbarBottom.vue")['default']
export const UiNavbarTop: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/NavbarTop.vue")['default']
export const UiOverlay: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Overlay/Overlay.vue")['default']
export const UiOverlayTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Overlay/types")['default']
export const UiPageBuilder: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PageBuilder.vue")['default']
export const UiPageContainer: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PageContainer.vue")['default']
export const UiPagination: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Pagination/Pagination.vue")['default']
export const UiPaginationTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Pagination/types")['default']
export const UiProductCard: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCard/ProductCard.vue")['default']
export const UiProductCardTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCard/types")['default']
export const UiProductCardHorizontal: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCardHorizontal/ProductCardHorizontal.vue")['default']
export const UiProductCardHorizontalTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCardHorizontal/types")['default']
export const UiPurchaseCard: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PurchaseCard/PurchaseCard.vue")['default']
export const UiPurchaseCardTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PurchaseCard/types")['default']
export const UiQuantitySelector: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/QuantitySelector/QuantitySelector.vue")['default']
export const UiQuantitySelectorTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/QuantitySelector/types")['default']
export const UiRadialProgress: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/RadialProgress.vue")['default']
export const UiReview: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Review/Review.vue")['default']
export const UiReviewTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Review/types")['default']
export const UiScrollTop: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ScrollTop.vue")['default']
export const UiSearch: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Search.vue")['default']
export const UiTag: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Tag/Tag.vue")['default']
export const UiTagTypes: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Tag/types")['default']
export const UiVsfLogo: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/VsfLogo.vue")['default']
export const UiFormsBooleanInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/BooleanInput.vue")['default']
export const UiFormsDateTime: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DateTime.vue")['default']
export const UiFormsDirectusFormElement: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DirectusFormElement.vue")['default']
export const UiFormsDynamicTableElement: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DynamicTableElement.vue")['default']
export const UiFormsFileInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/FileInput.vue")['default']
export const UiFormsFormField: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/FormField.vue")['default']
export const UiFormsRelationSelect: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/RelationSelect.vue")['default']
export const UiFormsRepeaterInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/RepeaterInput.vue")['default']
export const UiFormsSelectInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/SelectInput.vue")['default']
export const UiFormsTextArea: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TextArea.vue")['default']
export const UiFormsTextInput: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TextInput.vue")['default']
export const UiFormsTiptapEditor: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TiptapEditor.vue")['default']
export const UiForms[collection]: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/[collection].vue")['default']
export const UiStudioBuilder: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/builder.vue")['default']
export const UiStudioDocument: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/document.vue")['default']
export const UiStudioEmail: typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/email.vue")['default']
export const BlocksLogoutButton: typeof import("../node_modules/@mframework/layer-auth/app/components/blocks/logoutButton.vue")['default']
export const SearchAccountInfo: typeof import("../node_modules/@mframework/layer-search/app/components/SearchAccountInfo.vue")['default']
export const SearchEmojiInfo: typeof import("../node_modules/@mframework/layer-search/app/components/SearchEmojiInfo.vue")['default']
export const SearchHashtagInfo: typeof import("../node_modules/@mframework/layer-search/app/components/SearchHashtagInfo.vue")['default']
export const SearchResult: typeof import("../node_modules/@mframework/layer-search/app/components/SearchResult.vue")['default']
export const SearchResultSkeleton: typeof import("../node_modules/@mframework/layer-search/app/components/SearchResultSkeleton.vue")['default']
export const SearchWidget: typeof import("../node_modules/@mframework/layer-search/app/components/SearchWidget.vue")['default']
export const AtomsBaseButton: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseButton.vue")['default']
export const AtomsBaseCard: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseCard.vue")['default']
export const AtomsBaseCheckbox: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseCheckbox.vue")['default']
export const AtomsBaseLogo: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseLogo.vue")['default']
export const AtomsBaseText: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseText.vue")['default']
export const AtomsBaseTitle: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseTitle.vue")['default']
export const AtomsDiscordIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/DiscordIcon.vue")['default']
export const AtomsGithubIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/GithubIcon.vue")['default']
export const AtomsHalfSolidStarIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/HalfSolidStarIcon.vue")['default']
export const AtomsSelectArrow: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/SelectArrow.vue")['default']
export const AtomsSolidStarIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/SolidStarIcon.vue")['default']
export const AtomsStarIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/StarIcon.vue")['default']
export const AtomsTwitterIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/TwitterIcon.vue")['default']
export const AtomsWebIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/WebIcon.vue")['default']
export const AtomsXIcon: typeof import("../node_modules/@mframework/layer-search/app/components/atoms/XIcon.vue")['default']
export const FeaturesAutocomplete: typeof import("../node_modules/@mframework/layer-search/app/components/features/autocomplete.vue")['default']
export const FeaturesSearchkitSearch: typeof import("../node_modules/@mframework/layer-search/app/components/features/searchkitSearch.vue")['default']
export const Filters: typeof import("../node_modules/@mframework/layer-search/app/components/filters/filters.vue")['default']
export const MoleculesBaseSelect: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/BaseSelect.vue")['default']
export const MoleculesPageNumber: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/PageNumber.vue")['default']
export const MoleculesRangeSlider: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/RangeSlider.vue")['default']
export const MoleculesSearchInput: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/SearchInput.vue")['default']
export const MoleculesSocialLink: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/SocialLink.vue")['default']
export const MoleculesStarRating: typeof import("../node_modules/@mframework/layer-search/app/components/molecules/StarRating.vue")['default']
export const OrganismsLoadingIndicator: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/LoadingIndicator.vue")['default']
export const OrganismsMeiliSearchBar: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchBar.vue")['default']
export const OrganismsMeiliSearchFacetFilter: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchFacetFilter.vue")['default']
export const OrganismsMeiliSearchLoadingProvider: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchLoadingProvider.vue")['default']
export const OrganismsMeiliSearchPagination: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchPagination.vue")['default']
export const OrganismsMeiliSearchProvider: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchProvider.vue")['default']
export const OrganismsMeiliSearchRangeFilter: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchRangeFilter.vue")['default']
export const OrganismsMeiliSearchRatingFilter: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchRatingFilter.vue")['default']
export const OrganismsMeiliSearchResults: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchResults.vue")['default']
export const OrganismsMeiliSearchSorting: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchSorting.vue")['default']
export const OrganismsMeiliSearchStats: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchStats.vue")['default']
export const OrganismsProductCard: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/ProductCard.vue")['default']
export const OrganismsTheNavbar: typeof import("../node_modules/@mframework/layer-search/app/components/organisms/TheNavbar.vue")['default']
export const ResultsAudioSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/audioSearch.vue")['default']
export const ResultsBooksSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/booksSearch.vue")['default']
export const ResultsFinanceSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/financeSearch.vue")['default']
export const ResultsImageSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/imageSearch.vue")['default']
export const ResultsMusicSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/musicSearch.vue")['default']
export const ResultsNewsSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/newsSearch.vue")['default']
export const ResultsSpaceSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/spaceSearch.vue")['default']
export const ResultsSpacesSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/spacesSearch.vue")['default']
export const ResultsTravelSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/travelSearch.vue")['default']
export const ResultsVideoSearch: typeof import("../node_modules/@mframework/layer-search/app/components/results/videoSearch.vue")['default']
export const Search: typeof import("../node_modules/@mframework/layer-search/app/components/search.vue")['default']
export const TemplatesHomeTemplate: typeof import("../node_modules/@mframework/layer-search/app/components/templates/HomeTemplate.vue")['default']
export const WidgetsClearRefinements: typeof import("../node_modules/@mframework/layer-search/app/components/widgets/ClearRefinements.vue")['default']
export const WidgetsNoResults: typeof import("../node_modules/@mframework/layer-search/app/components/widgets/NoResults.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const TiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3/menus")['FloatingMenu']
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3/menus")['BubbleMenu']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyBlocksLogo: LazyComponent<typeof import("../app/components/blocks/logo.vue")['default']>
export const LazyMenusFooter: LazyComponent<typeof import("../app/components/menus/Footer.vue")['default']>
export const LazyMenusHeader: LazyComponent<typeof import("../app/components/menus/Header.vue")['default']>
export const LazyMenusEcosystemmenu: LazyComponent<typeof import("../app/components/menus/ecosystemmenu.vue")['default']>
export const LazyMenusLowernav: LazyComponent<typeof import("../app/components/menus/lowernav.vue")['default']>
export const LazyMenusMobilesearch: LazyComponent<typeof import("../app/components/menus/mobilesearch.vue")['default']>
export const LazyMenusSidebarnav: LazyComponent<typeof import("../app/components/menus/sidebarnav.vue")['default']>
export const LazyMenusTopmenu: LazyComponent<typeof import("../app/components/menus/topmenu.vue")['default']>
export const LazyGallery: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/Gallery/Gallery.vue")['default']>
export const LazyHeading: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/Heading/Heading.vue")['default']>
export const LazyHeadingTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/Heading/types")['default']>
export const LazyMediaAudioGallery: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/audioGallery.vue")['default']>
export const LazyMediaDragDropUpload: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/dragDropUpload.vue")['default']>
export const LazyMediaFullscreenMediaModal: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/fullscreenMediaModal.vue")['default']>
export const LazyMediaImageCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/imageCard.vue")['default']>
export const LazyMediaImageGallery: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/imageGallery.vue")['default']>
export const LazyMediaCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaCard.vue")['default']>
export const LazyMediaCarousel: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaCarousel.vue")['default']>
export const LazyMediaFolderSidebar: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaFolderSidebar.vue")['default']>
export const LazyMediaPlayer: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaPlayer.vue")['default']>
export const LazyMediaSearchBar: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/mediaSearchBar.vue")['default']>
export const LazyMediaVideoGallery: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/media/videoGallery.vue")['default']>
export const LazyUiAccordionItem: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/AccordionItem/AccordionItem.vue")['default']>
export const LazyUiAccordionItemTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/AccordionItem/types")['default']>
export const LazyUiAlert: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Alert/Alert.vue")['default']>
export const LazyUiAlertTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Alert/types")['default']>
export const LazyUiBreadcrumbs: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Breadcrumbs/Breadcrumbs.vue")['default']>
export const LazyUiBreadcrumbsTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Breadcrumbs/types")['default']>
export const LazyUiCartProductCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CartProductCard/CartProductCard.vue")['default']>
export const LazyUiCartProductCardTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CartProductCard/types")['default']>
export const LazyUiCategoryCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CategoryCard/CategoryCard.vue")['default']>
export const LazyUiCategoryCardTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/CategoryCard/types")['default']>
export const LazyUiDisplay: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Display/Display.vue")['default']>
export const LazyUiDisplayTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Display/types")['default']>
export const LazyUiDivider: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Divider/Divider.vue")['default']>
export const LazyUiFooter: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Footer.vue")['default']>
export const LazyUiFormHelperText: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormHelperText.vue")['default']>
export const LazyUiFormLabel: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormLabel.vue")['default']>
export const LazyUiFormPasswordInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Form/FormPasswordInput.vue")['default']>
export const LazyUiHero: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Hero/Hero.vue")['default']>
export const LazyUiHeroTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Hero/types")['default']>
export const LazyUiMButton: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/MButton.vue")['default']>
export const LazyUiModal: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Modal/Modal.vue")['default']>
export const LazyUiModalTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Modal/types")['default']>
export const LazyUiMotionable: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Motionable.vue")['default']>
export const LazyUiNavbarBottom: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/NavbarBottom.vue")['default']>
export const LazyUiNavbarTop: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/NavbarTop.vue")['default']>
export const LazyUiOverlay: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Overlay/Overlay.vue")['default']>
export const LazyUiOverlayTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Overlay/types")['default']>
export const LazyUiPageBuilder: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PageBuilder.vue")['default']>
export const LazyUiPageContainer: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PageContainer.vue")['default']>
export const LazyUiPagination: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Pagination/Pagination.vue")['default']>
export const LazyUiPaginationTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Pagination/types")['default']>
export const LazyUiProductCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCard/ProductCard.vue")['default']>
export const LazyUiProductCardTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCard/types")['default']>
export const LazyUiProductCardHorizontal: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCardHorizontal/ProductCardHorizontal.vue")['default']>
export const LazyUiProductCardHorizontalTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ProductCardHorizontal/types")['default']>
export const LazyUiPurchaseCard: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PurchaseCard/PurchaseCard.vue")['default']>
export const LazyUiPurchaseCardTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/PurchaseCard/types")['default']>
export const LazyUiQuantitySelector: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/QuantitySelector/QuantitySelector.vue")['default']>
export const LazyUiQuantitySelectorTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/QuantitySelector/types")['default']>
export const LazyUiRadialProgress: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/RadialProgress.vue")['default']>
export const LazyUiReview: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Review/Review.vue")['default']>
export const LazyUiReviewTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Review/types")['default']>
export const LazyUiScrollTop: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/ScrollTop.vue")['default']>
export const LazyUiSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Search.vue")['default']>
export const LazyUiTag: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Tag/Tag.vue")['default']>
export const LazyUiTagTypes: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/Tag/types")['default']>
export const LazyUiVsfLogo: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/VsfLogo.vue")['default']>
export const LazyUiFormsBooleanInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/BooleanInput.vue")['default']>
export const LazyUiFormsDateTime: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DateTime.vue")['default']>
export const LazyUiFormsDirectusFormElement: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DirectusFormElement.vue")['default']>
export const LazyUiFormsDynamicTableElement: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/DynamicTableElement.vue")['default']>
export const LazyUiFormsFileInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/FileInput.vue")['default']>
export const LazyUiFormsFormField: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/FormField.vue")['default']>
export const LazyUiFormsRelationSelect: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/RelationSelect.vue")['default']>
export const LazyUiFormsRepeaterInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/RepeaterInput.vue")['default']>
export const LazyUiFormsSelectInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/SelectInput.vue")['default']>
export const LazyUiFormsTextArea: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TextArea.vue")['default']>
export const LazyUiFormsTextInput: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TextInput.vue")['default']>
export const LazyUiFormsTiptapEditor: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/TiptapEditor.vue")['default']>
export const LazyUiForms[collection]: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/forms/[collection].vue")['default']>
export const LazyUiStudioBuilder: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/builder.vue")['default']>
export const LazyUiStudioDocument: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/document.vue")['default']>
export const LazyUiStudioEmail: LazyComponent<typeof import("../node_modules/@mframework/layer-shared/app/components/ui/studio/email.vue")['default']>
export const LazyBlocksLogoutButton: LazyComponent<typeof import("../node_modules/@mframework/layer-auth/app/components/blocks/logoutButton.vue")['default']>
export const LazySearchAccountInfo: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchAccountInfo.vue")['default']>
export const LazySearchEmojiInfo: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchEmojiInfo.vue")['default']>
export const LazySearchHashtagInfo: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchHashtagInfo.vue")['default']>
export const LazySearchResult: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchResult.vue")['default']>
export const LazySearchResultSkeleton: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchResultSkeleton.vue")['default']>
export const LazySearchWidget: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/SearchWidget.vue")['default']>
export const LazyAtomsBaseButton: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseButton.vue")['default']>
export const LazyAtomsBaseCard: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseCard.vue")['default']>
export const LazyAtomsBaseCheckbox: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseCheckbox.vue")['default']>
export const LazyAtomsBaseLogo: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseLogo.vue")['default']>
export const LazyAtomsBaseText: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseText.vue")['default']>
export const LazyAtomsBaseTitle: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/BaseTitle.vue")['default']>
export const LazyAtomsDiscordIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/DiscordIcon.vue")['default']>
export const LazyAtomsGithubIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/GithubIcon.vue")['default']>
export const LazyAtomsHalfSolidStarIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/HalfSolidStarIcon.vue")['default']>
export const LazyAtomsSelectArrow: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/SelectArrow.vue")['default']>
export const LazyAtomsSolidStarIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/SolidStarIcon.vue")['default']>
export const LazyAtomsStarIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/StarIcon.vue")['default']>
export const LazyAtomsTwitterIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/TwitterIcon.vue")['default']>
export const LazyAtomsWebIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/WebIcon.vue")['default']>
export const LazyAtomsXIcon: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/atoms/XIcon.vue")['default']>
export const LazyFeaturesAutocomplete: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/features/autocomplete.vue")['default']>
export const LazyFeaturesSearchkitSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/features/searchkitSearch.vue")['default']>
export const LazyFilters: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/filters/filters.vue")['default']>
export const LazyMoleculesBaseSelect: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/BaseSelect.vue")['default']>
export const LazyMoleculesPageNumber: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/PageNumber.vue")['default']>
export const LazyMoleculesRangeSlider: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/RangeSlider.vue")['default']>
export const LazyMoleculesSearchInput: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/SearchInput.vue")['default']>
export const LazyMoleculesSocialLink: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/SocialLink.vue")['default']>
export const LazyMoleculesStarRating: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/molecules/StarRating.vue")['default']>
export const LazyOrganismsLoadingIndicator: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/LoadingIndicator.vue")['default']>
export const LazyOrganismsMeiliSearchBar: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchBar.vue")['default']>
export const LazyOrganismsMeiliSearchFacetFilter: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchFacetFilter.vue")['default']>
export const LazyOrganismsMeiliSearchLoadingProvider: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchLoadingProvider.vue")['default']>
export const LazyOrganismsMeiliSearchPagination: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchPagination.vue")['default']>
export const LazyOrganismsMeiliSearchProvider: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchProvider.vue")['default']>
export const LazyOrganismsMeiliSearchRangeFilter: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchRangeFilter.vue")['default']>
export const LazyOrganismsMeiliSearchRatingFilter: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchRatingFilter.vue")['default']>
export const LazyOrganismsMeiliSearchResults: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchResults.vue")['default']>
export const LazyOrganismsMeiliSearchSorting: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchSorting.vue")['default']>
export const LazyOrganismsMeiliSearchStats: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/MeiliSearchStats.vue")['default']>
export const LazyOrganismsProductCard: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/ProductCard.vue")['default']>
export const LazyOrganismsTheNavbar: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/organisms/TheNavbar.vue")['default']>
export const LazyResultsAudioSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/audioSearch.vue")['default']>
export const LazyResultsBooksSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/booksSearch.vue")['default']>
export const LazyResultsFinanceSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/financeSearch.vue")['default']>
export const LazyResultsImageSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/imageSearch.vue")['default']>
export const LazyResultsMusicSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/musicSearch.vue")['default']>
export const LazyResultsNewsSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/newsSearch.vue")['default']>
export const LazyResultsSpaceSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/spaceSearch.vue")['default']>
export const LazyResultsSpacesSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/spacesSearch.vue")['default']>
export const LazyResultsTravelSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/travelSearch.vue")['default']>
export const LazyResultsVideoSearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/results/videoSearch.vue")['default']>
export const LazySearch: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/search.vue")['default']>
export const LazyTemplatesHomeTemplate: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/templates/HomeTemplate.vue")['default']>
export const LazyWidgetsClearRefinements: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/widgets/ClearRefinements.vue")['default']>
export const LazyWidgetsNoResults: LazyComponent<typeof import("../node_modules/@mframework/layer-search/app/components/widgets/NoResults.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyTiptapEditorContent: LazyComponent<typeof import("@tiptap/vue-3")['EditorContent']>
export const LazyTiptapFloatingMenu: LazyComponent<typeof import("@tiptap/vue-3/menus")['FloatingMenu']>
export const LazyTiptapBubbleMenu: LazyComponent<typeof import("@tiptap/vue-3/menus")['BubbleMenu']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
